# Generated by Django 4.0.4 on 2022-04-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raseetstore', '0001_initial'),
    ]

    operations = [
    ]
