# Generated by Django 4.0.4 on 2022-04-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raseetstore', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_info', models.TextField()),
                ('when_to_use', models.CharField(max_length=200)),
                ('how_to_use', models.TextField()),
                ('benefits', models.TextField()),
                ('side_effects', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Salt_composition',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='', max_length=150),
        ),
    ]
